add katex functionality
zen-mapper/zen-mapper pull request #31
Opened 2024-11-22 00:33 UTC by Jamiller137

No prerendering yet since that requires nodejs. I mainly just followed their documentation.

2024-11-22 00:57 UTC, Jamiller137 commented on examples/custom_clusterer.py
I'm not sure why this is tagged as a difference.

2024-11-26 17:56 UTC, erooke commented on examples/custom_clusterer.py
There was a newline character at the bottom of the file which was deleted

2024-11-26 19:09 UTC, erooke requested changes
Generally looks good, some small changes and it should be ready to merge

2024-11-26 21:36 UTC, closed without merging

2024-11-26 21:40 UTC, erooke commented
Thanks for the contribution! In future if you could avoid merging main into feature branches that makes merging a lot simpler. If you want to update your branch to follow main `git rebase origin/main` will result in a much simpler merge procedure later.

2024-11-26 21:48 UTC, Jamiller137 commented
Oh I see what you mean on the network graph. Sounds good, thanks!

-Jacob

On Tue, Nov 26, 2024 at 3:40 PM Ethan Rooke ***@***.***>
wrote:

> Thanks for the contribution! In future if you could avoid merging main
> into feature branches that makes merging a lot simpler. If you want to
> update your branch to follow main git rebase origin/main will result in a
> much simpler merge procedure later.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zen-mapper/zen-mapper/pull/31#issuecomment-2501985311>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFXZNS5S5L3JZ6SSXNRIGP32CTTE3AVCNFSM6AAAAABSIG7C3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMBRHE4DKMZRGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>